SIMULATOR:
  dim: 3
  gravity: [0., -3.8, 0.]
  default_dt: 5.e-4
  quality: 1.
  padding: [28, 3, 28]
  needs_grad: False
  use_checkpointing: False
  max_substeps_local: 2
  max_substeps: 999999 # set to a super large number
  max_num_particles: 150000
  use_dynamic_field: False
  checkpoint_cache_device: torch_cpu
  base_active_materials: [Plasticine]
  max_actuation: 10
ENVIRONMENT:
  objective: move_forward
  objective_config:
    reward_mode: per_step_velocity
    forward_direction: [1., 0., 0.]
    max_episode_steps: 200
  ITEMS:
    # Terrain
    - type: Static.BoundingBox # World boundary
      semantic_id: 0 # static obstacle
    - type: Static.Terrain
      surface: Surface.Slip
      semantic_id: 0 # static obstacle
      friction: 0.5
      min_height: 0.1
      max_height: 0.1
  # Environment-specific
  use_renderer: False
  actuation_strength: 0.3
  observation_space: [time, com]
  design_space: pbr
  design_space_config:
    n_actuators: 10
    initial_principle_direction: [1., 0., 0.]
    p_rho_lower_bound_mul: 0.1
    base_shape:
      type: Primitive.Box
      size: [0.1, 0.06, 0.1]
      sample_density: 48
      initial_position: [0.35, 0.04, 0.4]
      initial_velocity: [0., 0., 0.]
      material: DiffAquaMuscle
      particle_id: 3 # used as robot id
      particle_info:
        p_rho_0: 1.e+3
        E_0: 1.e+4
      semantic_id: 3
  CUSTOM:
    randomize_terrain: False
    has_matter_on_ground: True
    matter_id: 4
    matter_materials: [Plasticine]
    matter_thickness: 0.02
    matter_sample_density: 8
    matter_semantic_id: 4
    matter_youngs_modulus: 1.e+5
    matter_padding: [32, 3, 32]
RENDERER:
  type: ggui
  GGUI:
    ambient_light: [0.5, 0.5, 0.5]
    camera_lookat: [0.5, 0.05, 0.5] # horizontal look
    camera_position: [0.5, 0.3, 0.0]
    particle_radius: 0.002
    particle_coloring_mode: actuation
    ground_surface_cmap: textures/clay.png
