SIMULATOR:
  dim: 3
  gravity: [0., -3.8, 0.]
  default_dt: 2e-4
  quality: 1.
  padding: [32, 3, 32]
  needs_grad: True
  use_checkpointing: True
  max_substeps_local: 20
  max_substeps: 9000
  max_num_particles: 240000
  use_dynamic_field: False
  checkpoint_cache_device: torch_cpu
  base_active_materials: [Water]
  max_actuation: 10
ENVIRONMENT:
  objective: move_forward
  objective_config:
    reward_mode: per_step_velocity
    forward_direction: [1., 0., 0.]
    max_episode_steps: 200
  ITEMS:
    # Terrain
    - type: Static.BoundingBox # World boundary
      semantic_id: 0 # static obstacle
    - type: Static.Terrain
      surface: Surface.Slip
      semantic_id: 0 # static obstacle
      friction: 0.0
      min_height: 0.0
      max_height: 0.0
  # Environment-specific
  use_renderer: False
  actuation_strength: 0.4
  observation_space: [time, com]
  design_space: vbr
  design_space_config:
    n_actuators: 10
    initial_principle_direction: [1., 0., 0.]
    p_rho_lower_bound_mul: 0.1
    voxel_resolution: [60, 35, 26] # will be round to (64, 64, 32)
    base_shape:
      type: Primitive.Box
      size: [0.1, 0.1, 0.1] # voxelizer if size (64, 64, 32) --> only need to consider the largest
      sample_density: 48
      initial_position: [0.4, 0.03, 0.5]
      initial_velocity: [0., 0., 0.]
      material: DiffAquaMuscle
      particle_info:
        muscle_direction: [1., 0., 0.]
        p_rho_0: 7.5e+2 # Compensate for denser particles compared to PBR # 1.e+3
        E_0: 1.e+5
      semantic_id: 3
  CUSTOM:
    randomize_terrain: False
    matter_semantic_id: 131073
    matter_id: 131073 # NOTE: to be rendered after robot (for handling bug in ggui)
    matter_depth: 0.1 # must be larger than terrain max height
    matter_sample_density: 2
    matter_density: 1.e+3
RENDERER:
  type: ggui
  GGUI:
    ambient_light: [1., 1., 1.]
    camera_lookat: [0., -6.28, 0.] # top-down
    camera_position: [0.5, 0.6, 0.5]
    particle_radius: 0.0015
    particle_coloring_mode: actuation
    ground_surface_cmap: textures/ocean.png
